dist: trusty
language: node_js
node_js:
- "stable"
before_script:
# karma - http://karma-runner.github.io/0.8/plus/Travis-CI.html
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# global gulp + karma + cat
- npm install -g karma
- npm install -g cat
- npm install
- npm install rxjs@rc
# build all
- npm run build:all
script: 
# run tests
- npm run test:publish
after_script:
# run coveralls
- npm run coveralls
