dist: trusty
language: node_js
node_js:
- "stable"
before_script:
# ------ Global setup ---------#
- npm i -g lerna
# ------ Delivery setup -------#
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g karma # info - http://karma-runner.github.io/0.8/plus/Travis-CI.html
- npm install -g cat
- npm install rxjs
script: 
# Run all tests with global lerna command
- npm run lerna:travis
